BINARY LOGISTIC REGRESSION

In [ ]:
#Binary Logistic Regression

import numpy as np
import pandas as pd

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def predict(features, coefficients, intercept):
    z = np.dot(features, coefficients) + intercept
    probability = sigmoid(z)
    return 1 if probability >= 0.5 else 0

def main():
    # Load datasets
    # data_file = input("Enter path for dataset CSV: ")
    # coeff_file = input("Enter path for coefficients CSV: ")
    # intercept_file = input("Enter path for intercept CSV: ")

    data = pd.read_csv("/content/binary_logistic_regression_data.csv")
    coefficients = pd.read_csv("/content/separate_coefficients.csv", index_col=0).values.flatten()
    intercept = pd.read_csv("/content/intercept.csv").values[0, 0]

    # Extract feature columns dynamically
    feature_columns = [col for col in data.columns if col.lower() not in ['purchased']]

    # Take new datapoint input
    print("Enter values for new datapoint:")
    new_datapoint = []
    for feature in feature_columns:
        value = float(input(f"{feature}: "))
        new_datapoint.append(value)

    # Convert to numpy array
    new_datapoint = np.array(new_datapoint)

    # Predict class
    predicted_class = predict(new_datapoint, coefficients, intercept)
    print(f"Predicted Class: {predicted_class}")

if __name__ == "__main__":
    main()

**MULTINOMIAL LOGISTIC REGRESSION**

---






In [16]:
import numpy as np
import pandas as pd

# Load the dataset
data = pd.read_csv('/content/mlr - Sheet1.csv')
coefficients = pd.read_csv('/content/mlr - Sheet2.csv1')

# Extract coefficients (shape: 6 features x 3 classes)
weights = coefficients.iloc[:, 1:].values  # Use Class 0, 1, 2 columns directly

# Softmax function
def softmax(z):
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

# Function to predict class for new data points
def predict_new_data():
    # Input new data points
    print("Enter the following details for the new data point:")
    age = float(input("Age: "))
    income = float(input("Income: "))
    gender = float(input("Gender (0 for Female, 1 for Male): "))
    marital_status = float(input("Marital Status (0 for Unmarried, 1 for Married): "))
    credit_score = float(input("Credit Score: "))
    shopping_frequency = float(input("Shopping Frequency: "))

    # Create a new data point as a numpy array
    new_data = np.array([age, income, gender, marital_status, credit_score, shopping_frequency]).reshape(1, -1)

    # Calculate logits for the new data point
    logits = np.dot(new_data, weights)

    # Debugging: Print logits
    print("\nLogits (before softmax):", logits)

    # Calculate probabilities using softmax
    probabilities = softmax(logits)

    # Predict the class with the highest probability
    predicted_class = np.argmax(probabilities, axis=1)

    # Output results
    print("\nProbabilities for each class (Class 0, Class 1, Class 2):")
    print(np.round(probabilities, 4))
    print(f"Predicted Class: {predicted_class[0]}")

# Run the prediction function
predict_new_data()

Enter the following details for the new data point:
Age: 45
Income: 2
Gender (0 for Female, 1 for Male): 1
Marital Status (0 for Unmarried, 1 for Married): 1
Credit Score: 600
Shopping Frequency: 8

Logits (before softmax): [[ 0.8561 -0.9464  0.031 ]]

Probabilities for each class (Class 0, Class 1, Class 2):
[[0.6238 0.1029 0.2733]]
Predicted Class: 0


In [18]:
import numpy as np
import pandas as pd

# Load the dataset
data = pd.read_csv('/content/mlr - Sheet1.csv')
coefficients = pd.read_csv('/content/mlr - Sheet2.csv')

# Extract coefficients (shape: 6 features x 3 classes)
weights = coefficients.iloc[:, 1:].values  # Use Class 0, 1, 2 columns directly

# Softmax function
def softmax(z):
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

# Function to predict class for new data points
def predict_new_data():
    # Input new data points
    print("Enter the following details for the new data point:")
    age = float(input("Age: "))
    income = float(input("Income: "))
    gender = float(input("Gender (0 for Female, 1 for Male): "))
    marital_status = float(input("Marital Status (0 for Unmarried, 1 for Married): "))
    credit_score = float(input("Credit Score: "))
    shopping_frequency = float(input("Shopping Frequency: "))

    # Create a new data point as a numpy array
    new_data = np.array([age, income, gender, marital_status, credit_score, shopping_frequency]).reshape(1, -1)

    # Calculate logits for the new data point
    logits = np.dot(new_data, weights)

    # Debugging: Print logits
    print("\nLogits (before softmax):", logits)

    # Calculate probabilities using softmax
    probabilities = softmax(logits)

    # Predict the class with the highest probability
    predicted_class = np.argmax(probabilities, axis=1)

    # Output results
    print("\nProbabilities for each class (Class 0, Class 1, Class 2):")
    print(np.round(probabilities, 4))
    print(f"Predicted Class: {predicted_class[0]}")

# Run the prediction function
predict_new_data()

Enter the following details for the new data point:
Age: 30
Income: 3
Gender (0 for Female, 1 for Male): 1
Marital Status (0 for Unmarried, 1 for Married): 1
Credit Score: 700
Shopping Frequency: 3

Logits (before softmax): [[ 0.1835  0.2127 -0.466 ]]

Probabilities for each class (Class 0, Class 1, Class 2):
[[0.3919 0.4035 0.2047]]
Predicted Class: 1


In [20]:
import numpy as np
import pandas as pd

data = pd.read_csv('/content/mlr - Sheet1.csv')
coefficients = pd.read_csv('/content/mlr - Sheet2.csv')
weights = coefficients.iloc[:, 1:].values

def softmax(z):
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)
def predict_new_data():
    print("Enter the following details for the new data point:")
    age = float(input("Age: "))
    income = float(input("Income: "))
    gender = float(input("Gender (0 for Female, 1 for Male): "))
    marital_status = float(input("Marital Status (0 for Unmarried, 1 for Married): "))
    credit_score = float(input("Credit Score: "))
    shopping_frequency = float(input("Shopping Frequency: "))
    new_data = np.array([age, income, gender, marital_status, credit_score, shopping_frequency]).reshape(1, -1)
    logits = np.dot(new_data, weights)
    print("\nLogits (before softmax):", logits)
    probabilities = softmax(logits)
    predicted_class = np.argmax(probabilities, axis=1)
    print("\nProbabilities for each class (Class 0, Class 1, Class 2):")
    print(np.round(probabilities, 4))
    print(f"Predicted Class: {predicted_class[0]}")
predict_new_data()

Enter the following details for the new data point:
Age: 13
Income: 0
Gender (0 for Female, 1 for Male): 1
Marital Status (0 for Unmarried, 1 for Married): 0
Credit Score: 468
Shopping Frequency: 8

Logits (before softmax): [[ 0.7267 -0.9192  0.1464]]

Probabilities for each class (Class 0, Class 1, Class 2):
[[0.5706 0.11   0.3194]]
Predicted Class: 0
