In [2]:
import numpy as np
import pandas as pd

file_path = "/content/f1 - Sheet1 (1).csv"
df = pd.read_csv(file_path, header=None)
data = df.values

n = data.shape[0]
m = data.shape[1]

mean_vector = np.array([np.sum(col) / n for col in data.T])

deviations = data - mean_vector
cov_matrix = np.zeros((m, m))
for i in range(m):
    for j in range(m):
        cov_matrix[i, j] = np.sum(deviations[:, i] * deviations[:, j]) / (n - 1)
std_devs = np.sqrt(np.diag(cov_matrix))
corr_matrix = np.zeros((m, m))
for i in range(m):
    for j in range(m):
        corr_matrix[i, j] = cov_matrix[i, j] / (std_devs[i] * std_devs[j])

print("Mean Vector:")
print(np.around(mean_vector, 6))
print("\nCovariance Matrix:")
print(np.around(cov_matrix, 6))
print("\nCorrelation Matrix:")
print(np.around(corr_matrix, 6))


Mean Vector:
[6.466667 4.466667 6.933333]

Covariance Matrix:
[[1.552381 0.409524 0.17619 ]
 [0.409524 1.980952 0.17619 ]
 [0.17619  0.17619  1.638095]]

Correlation Matrix:
[[1.       0.23353  0.110488]
 [0.23353  1.       0.097808]
 [0.110488 0.097808 1.      ]]
