In [5]:
import numpy as np
import pandas as pd

file_path = "/content/pca - Sheet1 (1).csv"
df = pd.read_csv(file_path, header=None)
data = df.values

n, m = data.shape

mean_vector = np.array([np.sum(col) / n for col in data.T])

deviations = data - mean_vector

cov_matrix = np.zeros((m, m))
for i in range(m):
    for j in range(m):
        cov_matrix[i, j] = np.sum(deviations[:, i] * deviations[:, j]) / (n - 1)

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

eigenvalues = np.real(eigenvalues)
eigenvectors = np.real(eigenvectors)

sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues_sorted = eigenvalues[sorted_indices]
eigenvectors_sorted = eigenvectors[:, sorted_indices]
pca_scores = deviations @ eigenvectors_sorted

print("\nCovariance Matrix:")
print(np.around(cov_matrix, 6))
print("\nEigenvalues (Sorted):")
print(np.around(eigenvalues_sorted, 6))
print("\nEigenvectors (Principal Components - Columns):")
print(np.around(eigenvectors_sorted, 6))
print("\nPCA Projected Data:")
print(np.around(pca_scores, 6))


Covariance Matrix:
[[ 8.2   9.15]
 [ 9.15 13.8 ]]

Eigenvalues (Sorted):
[20.56883  1.43117]

Eigenvectors (Principal Components - Columns):
[[-0.59472  -0.803933]
 [-0.803933  0.59472 ]]

PCA Projected Data:
[[ 5.649622 -1.442834]
 [ 3.02861   1.739978]
 [-2.356789 -0.495528]
 [-0.363416  0.517618]
 [-5.958027 -0.319235]]
